version: 2
jobs:
  build:
    docker:
      - image: vvakame/review:3.2
    steps:
      - checkout
      - run:
          name: Install Git LFS
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
            apt-get install git git-lfs openssh-client
            git lfs pull
      - run:
          name: Setup
          command: npm install
#      - restore_cache:
#          keys:
#            - npm-cache-{{ checksum "package-lock.json" }}
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: Build PDF
          command: npm run pdf
      - store_artifacts:
          path: ./articles/GREE-BookFest7.pdf
          destination: GREE-BookFest7.pdf
