version: 2
dependencies:
  override:
    # installing git-lfs
    - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
    - sudo apt-get install git-lfs=2.2.0
    - ssh git@github.com git-lfs-authenticate <user>/<project>.git download
    - git lfs pull
jobs:
  build:
    docker:
      - image: vvakame/review:3.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Setup
          command: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: Build PDF
          command: npm run pdf
      - store_artifacts:
          path: ./articles/GREE-BookFest7.pdf
          destination: GREE-BookFest7.pdf
